### ISSUE TITLE
pvmove not/badly provided over the API

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#29]
Right now the DBus API provides the `Move(src_pv, src_range, dst_pv, dst_range, move_opts)` method on the `Lv` objects. However, the syntax of the `pvmove` command doesn't require an LV as well as PE ranges being specified. What must be specified is a VG and thus I think the `Move()` method should be a method of `Vg` objects. And it should have a `Lv` (object path) as an optional parameter (passed in the `move_opts` as e.g. `"lv": "/some/obj/path"`). The ranges should be implemented (maybe they already are) in a way that passing `0, 0` as a source or destination range results in no range passed to LVM so that it's possible to not specify them. Things like `120, 0` should then result in `:120-` being passed to LVM.

**Comment by vpodzime** [comment]
One more thing I realized later -- the destination PV is also optional for the `pvmove` command so it could be `"/"` (an empty but valid object path).

**Comment by vpodzime** [comment]
Hmm, so the `pvmove` command doesn't allow for VG specification. But the PV's used as source and destination (if specified) have to belong to the same VG. So I still think that `Vg` objects are a good place for the `Move()` method.

**Comment by tasleson** [comment]
Yes, you are correct.  The pvmove doesn't require a LV, but it's one of the use cases.  I will look into adding this method to the VG, but we may need the method in both places or at least be able to accommodate providing the LV name too without resorting to using the optional parameters.

**Comment by tasleson** [comment]
Addressed with 06bbbc8958831f987c304504a8eb29d9d4da626f

Notes: 
- The pvmove can take multiple destinations with optional segment ranges so the signature for the destination was changed to `a(oii)`
- I left the Move method on the Lv and added same to Vg.  The parameter signatures are identical and the implementation uses the same code path (common function) with the only difference being the LV name used for the Lv use case.

@vpodzime Please check this out and see if this looks better.  I was thinking about making atomic a parameter too, not sure how much it's used.

**Comment by vpodzime** [comment]
Great, thanks! The only thing that is not ideal for me is that the `Move()` methods don't take the `tmo` parameter. It looks like they always return a `Job` object which kind of makes sense for such methods, but it is an inconsistency in the API and there might be cases where even the pvmove operation may be really fast and thus could fit into the "DBus timeout window". Could you please add the `tmo` parameter?

**Comment by tasleson** [comment]
Time out parameter added with f2b20995f5c70ddca1ec611e11f2a52519d1379b

**Comment by tasleson** [comment]
Time out added with commit f2b20995f5c70ddca1ec611e11f2a52519d1379b
