### ISSUE TITLE
pvscan not provided

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#30]
Should probably be a method of the `Manager` object.

**Comment by tasleson** [comment]
Added with commit 7ec013c92aeb5de66ec42bd972950225447cc233, please give it a spin and see if it's acceptable, thanks!

**Comment by vpodzime** [comment]
Looks great to me, thanks!

**Comment by vpodzime** [comment]
Hmm, one thing is a little bit weird -- are you sure the `device_paths` parameter should take an array of object_paths? I'd expect that to be something like `["/dev/sda1", "/dev/sdb1"]` which is an array of strings. I think DBus does some validations on object_paths and I'm not sure all device paths really match the criteria.

**Comment by tasleson** [comment]
I thought about making them strings, but thought the validation would work in our favor, however this could prove limiting in the future, I will switch them over to strings.
