### ISSUE TITLE
lvresize not provided

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#34]
There's no `Resize()` method of the `Lv` objects

**Comment by tasleson** [comment]
Added with commit 6dc4b0a149fb192b8d067335f4d27a5ffb382dab

Please review and let me know if this looks sufficient, Thanks!

**Comment by vpodzime** [comment]
Thanks! Generally I think the set of the parameters the `Resize()` method requires is too big. Many of them could/should be passed as the extra options. Some more comments in the commit...
