### ISSUE TITLE
No Activate() and Deactivate() methods on Lv objects

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#35]
These should be provided or the existing methods of the `Vg` objects should take an object path of an `Lv` as a parameter.

**Comment by tasleson** [comment]
Added with b5df3f73dd540db1353b069551335d36ed19969c

I also added the property Lv.Active `boolean` to determine if Lv is active or not with commit c85b8ef8a1ea246db3f1fb16855a69089d41a1b4

**Comment by vpodzime** [comment]
Looks great to me, thanks!
