### ISSUE TITLE
The Snapshot() method doesn't return a Job object

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#37]
I'm always getting `("/", "/")` as the return value.

**Comment by tasleson** [comment]
@vpodzime This appears to be working, were you calling them in incorrect order because of the inconsistency of the parameter order?

**Comment by vpodzime** [comment]
I don't think so. Maybe the path of the newly created (snapshot) LV isn't returned then? This is what I keep getting:
![d-feet_snapshot_ret](https://cloud.githubusercontent.com/assets/1044278/11653027/78b3ceb2-9d9b-11e5-9026-9f92258019ce.png)

**Comment by tasleson** [comment]
You are correct.  The unit test was incorrectly ensuring that the object path was always '/'.  The job object path was getting returned correctly, but not the newly created LV.  Fixed with 90774b9d45feef2339db95df4e814fa175a73434 Thanks!
