### ISSUE TITLE
Cannot specify PVs in the LvCreate*() methods

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#41]
`lvcreate` accepts a list of PVs (with PE ranges), but there's no nice way to do so over the DBus API. Also, but this is a separate issue, I don't think it is wise to have separate methods for different types of LVs. That way there will always be something missing somewhere and things like `--type`, `--stripes` and `--mirrors` can easily be specified in the extra options.

**Comment by tasleson** [comment]
@vpodzime One of my goals was to provide an API that was easier to use than the command line.  For example, `Lv.Snapshot` is really syntactic sugar for `lvcreate`.  I wanted the extra options to not be needed most of the time, just a small percentage of the time and to provide for future capabilities.

Yes we do need to have a way to specify all the possibilities, including PVs and PE ranges.  I will add a `LvCreate()` method that adds this and coupled with the `create_options` will allow the user to do anything that is possible on the command line.  

If the consensus is that users just want the command line, but wrapped up in dbus interface with some job control we can certainly move in that direction too.

**Comment by tasleson** [comment]
Add Vg.LvCreate with this 15051a1a42c16ccad48eeda5d949982b55c5bc19  Later if we find that the other create methods are not needed we can simply remove them.

**Comment by vpodzime** [comment]
Looks great, thanks! I agree that it would be nice for the DBus API to provide some higher-level API than the CLI provides right now. That's what libblockdev's LVM API does too, anyway. But there should also be a way to do things with a greater control. So adding a method like `Vg.LvCreate` is a great approach I think.
