### ISSUE TITLE
no 'data_lv' and 'medata_lv' properties on ThinPool objects

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#44]
These can be get with `lvs -o+data_lv,metadata_lv` and are useful for determining the relations between thin pool and it's internal LVs.

**Comment by vpodzime** [comment]
This depends on issue #32

**Comment by tasleson** [comment]
Should be addressed with 3a473ae2b5dfec9da39799d3adde946548b531be

**Comment by vpodzime** [comment]
Looks great! Thanks!
