### ISSUE TITLE
No way to merge a snapshot

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#45]
Not sure how this should be implemented, but the best way seems to be to add something like `com.redhat.lvmdbus1.Snapshot` interface with a `Merge()` method to snapshot LVs.

**Comment by tasleson** [comment]
@vpodzime This seems reasonable, initial pass with: 5a3f78cefcf5f40ef1b6e88c937adbcebd5f67bb

**Comment by vpodzime** [comment]
Looks good to me, I'll try it soon. Thanks!

**Comment by vpodzime** [comment]
Seems to be working great!
