### ISSUE TITLE
SegType not reported correctly

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#52]
The `SegType` property is not reported correctly for LVs. For example for my thin pool it says `linear` while it should be `thin-pool`. Also, for a raid1/mirror LV it reports linear. I checked the code and the reason for these wrong values is the way how segment type is determined for an LV -- from its PVs. Thin pool if of course just a linear LV from PVs perspective and raid1/mirror LV consists of two (or more) linear segments.

I think the segment type should be determined from the output of `lvs -osegtype` instead of from `pvs`.

**Comment by tasleson** [comment]
Fixed indirectly with 41aa28f74f76b0d4349bdbede8cac8c219f96539
