### ISSUE TITLE
No support for LVM Cache

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#54]
Right know, the DBus API completely ignores the LVM Cache functionality. While not being too commonly used now, it's expected to be used more and more often in the near future because it allows users to greatly combine benefits of cheap and rather slow devices (HDDs) and fast, but expensive devices (SSDs, nvme,...) mitigating the downsides they have separately. That's why _libblockdev_ and _Blivet_ provide at least a basic support for the LVM Cache functionality so far by using the LVM CLI.

The way LVM Cache works is that there is a special _cache pool_ LV (having a hidden data LV and a metadata LV just like thin pool) and the cache pool can be attached to an LV by which the LV becomes a cached LV (and the first letter in its `attr` changes to `C`). The resulting cached LV consists of (has internal LVs) the original LV (`_corig` appended to its name) and the cache pool.

_libblockdev_ and _Blivet_ allow a new cache pool as well as cached LV to be created, cache pool to be attached to and detached from an LV, to get a cache pool for a cached LV (like thin pool for a thin LV) and to get statistics for the cache. To provide this functionality using the DBus API, it would need to be extended to provide these functions:
- `Vg.CreateCachePool(data_lv, metadata_lv)` - to create a cache pool in a VG from two existing LVs
- `Lv.AttachCachePool(cache_pool)` - to attach a cache pool to an LV to make it cached
- `Lv.DetachCachePool()` - to detach a cache pool from a cached LV (doesn't make sense for non-cached LVs)

plus `Lv.CachePool` property to get the cache pool for a cached LV. The `Lv.DetachCachePool()` and `Lv.CachePool()` could be provided in some special _com.redhat.lvmdbus1.CachedLv_ interface provided only by cached LVs.

The stats are gathered directly from the _device-mapper_ by _libblockdev_, so this functionality is not required although it would be useful for other callers as well, I think.

**Comment by vpodzime** [comment]
Just adding a note that this is a low-priority issue because _libblockdev_ (and thus _Blivet_) can easily continue using the CLI for doing cache related things without any significant issues. The functionality is not used very often at this point (only supported in kickstart by _Anaconda_) and it's usually just a 2-3 steps (CLI runs) that are happening.

**Comment by tasleson** [comment]
@vpodzime This looks reasonable.  However, from an implementation approach I'm not sure how easily it will be to incrementally add an interface and then remove it from an object with the python library we are using (dbus specification clearly supports this).  I think the only way would be to remove the object, reconstruct it as an object which supports/does not support an interface.  For example, a LV attaches itself to a cache pool.  At that point that LV should gain the CachedLv interface and when the DetachCachePool is called it should lose that interface.  My main concern with removing and then re-adding is the race condition where a client is trying to reference the object while it's being removed and re-added.

**Comment by vpodzime** [comment]
Yeah, that sounds like a good plan. In fact, that's probably the right way to go because that's what actually happens "behind the scenes" when a cache pool is attached to an LV -- the original LV is "transformed" into `_corig` LV of the cached LV and thus at that moment the original LV becomes a hidden LV. So it might be best to just destroy and recreate the (DBus) objects.

**Comment by tasleson** [comment]
Addressed with 9720c699d6cbe059ff7d6a1170fc488bca8da3d9, see commit for details.
