### ISSUE TITLE
Detaching cache doesn't use enough force

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#56]
Detaching a cache pool with the `--uncache` option requires extra options to prevent interactive questions. This is the relevant chunk of code from *libblockdev's \* LVM plugin:

```
    /* need to both "assume yes" and "force" to get rid of the interactive
       questions in case of "--uncache" */
    gchar *args[6] = {"lvconvert", "-y", "-f", NULL, NULL, NULL};
```

Without those options the lvmdbusd hangs and when interrupted with 'Ctrl+C', it says:

> Do you really want to remove and DISCARD logical volume testCache? [y/n]:

**Comment by tasleson** [comment]
PR merged, thanks!
